# Generated by Django 6.0 on 2025-12-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0003_produit_description_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('paye', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['date_creation', 'prenom'], name='commande_co_date_cr_061b96_idx')],
            },
        ),
        migrations.CreateModel(
            name='LignesCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_commande', to='boutique.produit')),
            ],
        ),
    ]
