# Generated by Django 6.0 on 2025-12-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='id_stripe',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
