# Generated by Django 6.0 on 2025-12-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilite', models.BooleanField(blank=True, default=False)),
                ('quantite', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('statue', models.BooleanField(blank=True, default=False, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='boutique.categorie')),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['nom', 'date_creation', 'prix'], name='boutique_pr_nom_eeb3f0_idx')],
            },
        ),
    ]
